# Need this for static lib relocation
set(CMAKE_POSITION_INDEPENDENT_CODE YES)

set(ENV{DCORE_COMPILE_DEFINITIONS} "-DDCORE_PLAT_MAC")
set(DCORE_PLAT_MAC 1)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fPIC -g")
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -fPIC -g")
